apiVersion: apps/v1
kind: Statefulset
metadata:
  name: {{ include "clamav.fullname" . }}-mirror
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clamavMirror.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ include "clamav.fullname" . }}-mirror
  template:
    metadata:
      labels:
        name: {{ include "clamav.fullname" . }}-mirror
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.clamavMirror.image }}:{{ default .Chart.AppVersion .Values.clamavMirror.version }}"
        imagePullPolicy: Always
        resources: {{ toYaml .Values.clamavMirror.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /bytecode.cvd
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: LIGHTTPD_CONFIG
          value: /etc/config/lighttpd.conf
        - name: LIGHTTPD_ROOT
          value: /home/clam/mirror
        volumeMounts:
        - name: {{ include "clamav.fullname" . }}-mirror
          mountPath: /home/clam
        - name: config-volume
          mountPath: /etc/clamav/freshclam.conf
          subPath: freshclam.conf
        - name: config-volume
          mountPath: /etc/config/lighttpd.conf
          subPath: lighttpd.conf
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "clamav.fullname" . }}-mirror-config
  volumeClaimTemplates:
  - metadata:
      name: {{ include "clamav.fullname" . }}-mirror
    spec:
      storageClassName: {{ .Values.clamavMirror.volume.storageClass }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.clamavMirror.volume.size }}Gi
