apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-notify-config
data:
  freshclam.conf: |    
    DatabaseOwner clam
    DatabaseMirror http://localhost:8000
    TestDatabases yes
    LogVerbose yes

  lighttpd.conf: |
    server.document-root = "/var/lib/clamav/mirror/"

    server.port = 8080

    mimetype.assign = (
      ".htm" => "text/html", 
    )

    index-file.names = ( "index.htm" )
